name: Macos tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  macos:
    name: Mac Py${{ matrix.PYTHON_VERSION }}
    runs-on: macos-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'macos'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run tests
        shell: bash -l {0}
        run: |
          cd pyfasttrack/
          python3 -m pytest test
